# Config file for automatic testing at travis-ci.org
language: python

python:
  - "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python-gi

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - pip install coveralls

script:
  - coverage run --source datagrid_gtk3 setup.py test

after_success:
  - coveralls
