# Config file for automatic testing at travis-ci.org
language: python

python:
  - "2.7"

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-gi gir1.2-gtk-3.0

virtualenv:
  system_site_packages: true

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - pip install -e git+git@github.com:bosonogi/pygtkcompat.git#egg=pygtkcompat
  - pip install coveralls

script:
  - nosetests --with-coverage

after_success:
  - coveralls
