# Config file for automatic testing at travis-ci.org
language: python

python:
  - "2.7"

before_install:
  - sudo apt-get update
  - sudo apt-get install -qq python-gi gir1.2-gtk-3.0

virtualenv:
  system_site_packages: true

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - pip install coveralls

script:
  - coverage run --source datagrid_gtk3 setup.py test

after_success:
  - coveralls
